swagger: '2.0'
info:
  description: >-
    A basic `RESTful HTTP service` in `Go` for a simplified Tantan backend:
    `Adding users and swiping other people in order to find a match`.
  version: 1.0.0
  title: Tantan Demo
host: beanzhou.demo.tantan.com
basePath: /v1
tags:
  - name: Users
    description: Everything about User
  - name: RelationShips
    description: Relation of Users
schemes:
  - http
paths:
  /users:
    get:
      tags:
        - Users
      summary: List all users
      operationId: GetUserList
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '400':
          description: Invalid status value
    post:
      tags:
        - Users
      summary: Create a User
      operationId: CreateUser
      parameters:
        - in: body
          name: body
          description: username
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid input
  '/users/{user_id}/relationships':
    get:
      tags:
        - RelationShips
      summary: List relationship of the user
      operationId: GetRelationShips
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Relationships'
        '400':
          description: Invalid status value
  '/users/{user_id}/relationships/{other_user_id}':
    put:
      tags:
        - RelationShips
      summary: Create or Update Relationship
      operationId: UpdateRelationship
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
        - in: path
          name: other_user_id
          required: true
          type: integer
        - in: body
          name: body
          description: state
          required: true
          schema:
            $ref: '#/definitions/Relationships'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Relationships'
        '400':
          description: Invalid input
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      type:
        type: string
  Relationships:
    type: object
    properties:
      user_id:
        type: integer
        format: int64
      state:
        type: string
      type:
        type: string
